export * from "./auth";
export * from "./token";
export * from "./user";
export * from "./apiCausaMortandad";
export * from "./apiClasificacion";
export * from "./apiTipoRaza";
export * from "./apiMotivoPesaje";
export * from "./apiMotivoEntrada";
export * from "./apiMotivoSalida";
